### ISSUE TITLE
Way to remove storyblok_cache.js script?

### ISSUE THREAD

**Issue by kmukku** [storyblok/rendering-service#2]
I'm trying to produce XML with liquid templates but end of each template has following script block:

<script type="text/javascript" src="/_storyblok_cache.js" async></script>

Any way to remove it?

**Comment by DominikAngerer** [comment]
That is only possible if using a custom route. You can configure a new custom route in the Settings of your space -> Renderer Tab and add a file in your `views/` folder.

As an example: you can create a `sitemap.liquid` in your `views` folder, than you can hook it up with your Renderer as shown below.

![image](https://user-images.githubusercontent.com/7952803/104946544-85e37e80-59ba-11eb-8e3d-713ca44f6ef1.png)

You don't need to have `/sitemap*` in there if you only want to have `/sitemap.xml` on the left you can also just use that.

I would recommend our live-chat or discord for further support as this repository will not be monitored for support issues.
